# Generated by Django 5.0.1 on 2024-02-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='module_name', max_length=50)),
                ('dateTime', models.DateTimeField(auto_now=True, db_column='created_date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Syllsbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='syllabus_name', max_length=50)),
                ('description', models.TextField(db_column='syllabus_description', null=True)),
                ('logo', models.ImageField(db_column='syllabus_logo', default=None, upload_to='syllabus_logo')),
                ('dateTime', models.DateTimeField(auto_now=True, db_column='created_date_time')),
            ],
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='sub_module_name', max_length=50)),
                ('dateTime', models.DateTimeField(auto_now=True, db_column='created_date_time')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_services.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='syllsbus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_services.syllsbus'),
        ),
    ]
