# Generated by Django 5.0.1 on 2024-02-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Syllsbus',
            new_name='Syllabus',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='syllsbus',
            new_name='syllabus',
        ),
    ]
